# Site settings
title: Mexicali OpenSource
description: "Mexicali OpenSource es una comunidad de voluntarios que promueven el uso de las tecnologías de código libre en la ciudad."
baseurl: ""
url: "http://mxlos.org"
twitter_username: MxlOS
github_username:  MxlOS

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: :compressed